### PR TITLE
Manual merge/rebase of #207 and #224

### PR DESCRIPTION
**Pull request by dougmitarotonda**
Well, by the time I would be able to figure out merge/rebase I was worried my horizon of @hadley pulling these would close. So, I just forked the current master and made all of the changes, including the two suggestions from Hadley, in one single pull request here. Sorry about that, I know it is not preferred, but I want to help see these changes get pulled.

The one thing I did not do that @krlmlr mentioned was updating the .Rd file manually. Is that necessary? I would have thought that would update when Hadley builds the package. 

Anyway, let me know if you need anything else in order to get this pulled, and sorry for kind of hacking this together...

### CODE REVIEW

**Comment by dougmitarotonda** [comment]
I noticed the Travis CI build failed, but all of the tests passed when I ran the following locally. 

```
library(testthat)
library(plyr)
test_package("plyr")
```

**Comment by hadley** [comment]
Could you please add a bullet to NEWS? I'm working on fixing the build failure - you might need to re-merge master in again in an hour or so

**Comment by hadley** [comment]
And can you please list which issues this fixes?

**Comment by dougmitarotonda** [comment]
Done, see https://github.com/hadley/plyr/pull/236. Let me know if you need anything else. Note I looked through the defects and #225 is the same as #224, so I noted that as well and you will be able to close that issue.

**Comment by dougmitarotonda** [comment]
Just checking to see if you need anything else from me on this. I will be mostly out of pocket next week so if there is something I can help with this week, please let me know.

**Comment by hadley** [comment]
I don't see any changes to news.md - did you push?

**Comment by dougmitarotonda** [comment]
I put an updated pull request in here https://github.com/hadley/plyr/pull/237 last week. Is that not coming through correctly?

**Comment by hadley** [comment]
Oh I see - normally you just add it into the same branch so it all appears in one PR. No big deal

**Pull request merged**
