### PR TITLE
Approaching 90% coverage

### PR DESCRIPTION
**Pull request by krlmlr**
Testing is fun!

### CODE REVIEW

**Comment by hadley** [comment]
Can you add a bullet to news about deprecating `liply()`? (I assume because it doesn't work?)

**Comment by krlmlr** [comment]
`liply()`: I haven't tried if it works, but I have found zero matches on GitHub (which means all packages on CRAN) and no internal tests. This is intended as a honest statement that the code is there but you're on your own, given the now stable state of `plyr`. Do you prefer another solution?

**Comment by hadley** [comment]
@krlmlr yeah that's fine - it just needs a note in the news.

**Comment by hadley** [comment]
Thanks! Still no luck with turning coveralls on, and no response from support

**Comment by krlmlr** [comment]
That's too bad. http://codecov.io is good as well but needs an (encrypted) token that you'll have to add to `.travis.yml`.

**Comment by krlmlr** [comment]
Coveralls: Trying to look at coverage for `dplyr` at https://coveralls.io/builds/2263666/source?filename=.%2FR%2Ftally.R, I saw the following:

> SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

**Comment by hadley** [comment]
Thanks - that was the hint I needed. I revoked access in github and reauthed, and now it works :)

**Pull request merged**
