### PR TITLE
Add coverage analysis

### PR DESCRIPTION
**Pull request by krlmlr**
It's not horrifying at all, many modules already have full test coverage.

Need to register plyr with http://coveralls.io. Coverage for my fork: https://coveralls.io/r/krlmlr/plyr

README badge not yet included.

Do you want to keep the unused, unexported and untested `dots()` function?

### CODE REVIEW

**Comment by krlmlr** [comment]
5fc1a81 (the test for `d_ply`) requires a bleeding-edge version of `testthat` that fixes an issue with `with_mock`. Excluding it for now.

**Comment by hadley** [comment]
Just switched coveralls support on. Its fine to delete dots.  Can you merge/rebase and add the badge to the readme please?

**Comment by krlmlr** [comment]
Done, ready for merging.

**Comment by hadley** [comment]
Thanks!

**Comment by krlmlr** [comment]
https://coveralls.io still doesn't seem to know your repository.

**Comment by hadley** [comment]
Gah, it just seems to hang when I try and enable it

**Comment by krlmlr** [comment]
Strange. Worked for me for a small repo that was disabled previously. I removed my `plyr` fork from Coveralls, just in case this is the problem.

**Comment by hadley** [comment]
Still no luck - I've filed a support ticket.

**Pull request merged**
